version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build Starting on `date`
      - cd backend
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./backend/build/libs/*.jar)
artifacts:
  files:
    - backend/build/libs/*.jar
    - backend/scripts/**
    - backend/appspec.yml
  discard-paths: yes